#!/bin/sh

#
#
# 使用此脚本来为raspi3bp SD卡创建初始分区
#
#
set -e

parted -s ${DISK} mktable msdos
parted -s ${DISK} mkpart primary fat32 1 50
parted -s ${DISK} mkpart primary ext4 51 100%
sync

sleep 3

mkfs.fat /dev/${DISK}1
mkfs.ext4 /dev/${DISK}2

